name: sal
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_annotation: ^4.8.0
  validators: ^3.0.0
  chucker_flutter: ^1.3.6
  http_interceptor: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_lints: ^2.0.0

flutter: